spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB
  mvc:
    servlet:
      load-on-startup: 1
  output:
    ansi:
       enabled: ALWAYS
mybatis:
  type-aliases-package: com.zw.admin.server.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true

server:
  version:
    hud: 1.1.0
    fuse: 1.1.0
    das: 1.1.0
    doop: 1.1.0