spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://47.103.97.21:3307/fuliye_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    #url: jdbc:mysql://fftai2015.mysql.rds.aliyuncs.com:3306/platform?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://fftai2015.mysql.rds.aliyuncs.com:3306/platform_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: platform
    password: fftaiFLY!@#
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        allow: 127.0.0.1
  redis:
#    host: 47.103.109.120
    host: redis
    port: 6379
    timeout: 10000
    sentinels: redis:26379
    masterName: mymaster
    clients:
      maxTotal: 10
      maxIdle: 10
      testOnReturn: true
      testOnBorrow: true
    password: Fftai*^&2015
    database: 1
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    protocol: smtp
    test-connection: false
  activemq:
#    broker-url: tcp://127.0.0.1:61616
    broker-url: tcp://activeMQ:61616
    user: admin
    password: admin
    in-memory: false  #是否内置服务器
    pool:
      enabled: true  #是否用连接池
      max-connections: 10  #最大连接数
      idle-timeout: 30s
  jms:
    pub-sub-domain: true  #开启发布订阅模式
#    properties:
#      mail.smtp.auth: true
mail:
  from: shlingangkjc@163.com
  host: smtp.163.com
  password: kjc888888
  username: shlingangkjc

###文件，游戏路径,测试环境
uploadTmp:
  path: ${uploadTmp-path:c:/fuliyeweb/data/upload_tmp}
files:
  path: ${file-path:c:/fuliyeweb/files}
pic:
  path: ${pic-path:c:/fuliyeweb/GamePic}
commonpic:
  path: ${commonpic-path:c:/fuliyeweb/pic}
headImage:
  path: ${headImage-path:c:/fuliyeweb/headImage}
zip:
  path: ${zip-path:c:/fuliyeweb/zip/headImageZip}
bin:
  path: ${bin-path:c:/fuliyeweb/bin}

##文件，游戏路径,正式环境,文件为nas盘
#uploadTmp:
#  path: ${uploadTmp-path:z:/fuliyeweb/data/upload_tmp}
#files:
#  path: ${file-path:z:/fuliyeweb/files}
#pic:
#  path: ${pic-path:z:/fuliyeweb/GamePic}
#commonpic:
#  path: ${commonpic-path:z:/fuliyeweb/pic}
#headImage:
#  path: ${headImage-path:z:/fuliyeweb/headImage}
#zip:
#  path: ${zip-path:z:/fuliyeweb/zip/headImageZip}
#bin:
#  path: ${bin-path:z:/fuliyeweb/bin}

logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/admin-server.log
  maxsize: 30MB
token:
  expire:
    seconds: 86400

##http端口
http:
  port: 8080
  #100m
  maxPostSize: 104857600

##https端口
#server:
#  tomcat:
#    uri-encoding: UTF-8
#    # tomcat最大线程数，默认为200
#    max-threads: 800
#    # Tomcat启动初始化的线程数，默认值25
#    min-spare-threads: 30
#    # 配置post参数最大长度
#    max-http-post-size: -1
#  port: 443
#  servlet:
#    session:
#      timeout: 24h #30分钟，测试的话时间不能太短，否则不准。m是分钟单位，s是秒的单位，h是小时的单位，不写单位的话默认是毫秒
#  ssl:
#    #key-alias: tomcat
#    #key-store-type: PKCS12
#    key-store: D:\project\Backend\src\main\resources\5166310_api.fftai.com.pfx
#    key-store-password: 8jRs1uM0