pipeline {
    agent any
    triggers {
        GenericTrigger(
            genericVariables:[
                [key: 'ref', value: '$.ref']
            ],
            token: 'genericToken',
            printContributedVariables: true,
            printPostContent: true,
            regexpFilterText: '$ref',
            regexpFilterExpression: '^refs/heads/master$'
        )
    }
    stages {
        stage('Build') {
            steps {
                echo 'build master branch'
                sh './scripts/build.sh'
            }
        }
        stage('API_Test'){
            steps{
                echo 'APT test Area...'
                bat 'call scripts/test_JMeter.bat'
            }
        }
    }
    post{
        always{
            sh './scripts/kill-service.sh'
        }
        success{
            echo 'This workflow is successful!'
        }
        failure{
            echo 'This workflow is failed!'
        }
    }
}