pipeline {
    agent any
    triggers {
        GenericTrigger(
            genericVariables:[
                [key: 'commit_0', value: '$.commits.[0].message', defaultValue: ''],
                [key: 'commit_1', value: '$.commits.[1].message', defaultValue: ''],
                [key: 'ref', value: '$.ref', regexpFilter: '^refs/heads/', defaultValue: ''],
                [key: 'action', value: '$.action', defaultValue: ''],
                [key: 'base_repo', value: '$.pull_request.base.ref', defaultValue: '']
            ],
            token: 'genericToken',
            printContributedVariables: true,
            printPostContent: true,
            causeString: 'branch is $ref \n commit_0 is $commit_0 \n commit_1 is $commit_1 \n action is $action \n BRANCH_NAME is ' + env.BRANCH_NAME,
            regexpFilterText: '$commit_0'+'--@@--'+'$commit_1'+'--@@--'+'$ref',
            regexpFilterExpression: '(^(?!Merge).*--@@--(?!Merge)).*--@@--'+env.BRANCH_NAME
        )
    }
    stages {
        stage('Build') {
            steps {
                echo 'build master branch'
                sh './scripts/build.sh'
            }
        }
        stage('API_Test'){
            when {
                allOf{
                    branch 'master';
                    expression {
                        return '$action' == 'opened';
                    }
                }
            }
            steps{
                echo 'APT test Area...'
                bat 'call scripts/test_JMeter.bat'
            }
        }
    }
    post{
        always{
            sh './scripts/kill-service.sh'
        }
        success{
            echo 'This workflow is successful!'
        }
        failure{
            echo 'This workflow is failed!'
        }
    }
}