pipeline {
    agent any
    triggers {
        GenericTrigger(
            genericVariables:[
                [key: 'commit0', value: '$.commits.id'],
                [key: 'commit1', value: '$.commits.id[1]'],
                [key: 'ref', value: '$.ref'],
                [key: 'action', value: '$.action'],
                [key: 'base_repo', value: '$.pull_request.base.ref']
            ],
            token: 'genericToken',
            printContributedVariables: true,
            printPostContent: true,
            causeString: 'branch is $ref \n commit0 is $commit0 \n commit1 is $commit1 \n action is $action'
            //regexpFilterText: '$ref'+'-'+'$commit'+'-'+'$action'+'-'+'$base_repo',
            //regexpFilterExpression: '((^refs/heads/.+-.+--$)|(^--opened-master$))'
        )
    }
    stages {
        stage('Build') {
            steps {
                echo 'build master branch'
                sh './scripts/build.sh'
            }
        }
        stage('API_Test'){
            when {
                allOf{
                    branch 'master';
                    expression {
                        return '$action' == 'opened';
                    }
                }
            }
            steps{
                echo 'APT test Area...'
                bat 'call scripts/test_JMeter.bat'
            }
        }
    }
    post{
        always{
            sh './scripts/kill-service.sh'
        }
        success{
            echo 'This workflow is successful!'
        }
        failure{
            echo 'This workflow is failed!'
        }
    }
}